### ISSUE TITLE
Issue running setup.py with Windows 7 and Python 3.5

### ISSUE THREAD

**Issue by D-Chase-H** [mhogg/pyoctree#13]
This is the error I get in powershell:

WARNING: '' not a valid package name; please use only .-separated package names in setup.py
running install
Checking .pth file support in .\
F:\Python35\pythonw.exe -E -c pass
TEST FAILED: .\ does NOT support .pth files
error: bad install directory or PYTHONPATH

You are attempting to install a package to a directory that is not
on PYTHONPATH and which Python does not read ".pth" files from.  The
installation directory you specified (via --install-dir, --prefix, or
the distutils default setting) was:

    .\

and your PYTHONPATH environment variable currently contains:

    ''

Here are some of your options for correcting the problem:

* You can choose a different installation directory, i.e., one that is
  on PYTHONPATH or supports .pth files

* You can add the installation directory to the PYTHONPATH environment
  variable.  (It must then also be on PYTHONPATH whenever you run
  Python and want to use the package(s) you are installing.)

* You can set up the installation directory to support ".pth" files by
  using one of the approaches described here:

  https://setuptools.readthedocs.io/en/latest/easy_install.html#custom-installation-locations

Please make the appropriate changes for your system and try again.

**Comment by D-Chase-H** [comment]
I thought the issue was with using the release version for python 2.7, however when cloning the master branch, which should be compatible with python 3.5, I get the same isse.

Also, in setup.py on line 48 the class for Cython versions raises an error when trying to install with python 3.5:

Traceback (most recent call last):
  File "setup.py", line 48, in <module>
    class build_ext_compiler_check(build_ext):
NameError: name 'build_ext' is not defined

**Comment by mhogg** [comment]
Hi D-Chase-H,

I have deleted the setup.cfg file which was causing your first error (this used to be required, but apparently it is not anymore). 

Your second error related to 'build_ext' is most likely because Cython is not installed, and I was missing an import. This has been fixed in setup.py.

I have tested these changes in Python 2.7 and 3.6 on Windows 64 bit and have updated the latest master repo. Please try again and let me know if you have any further issues.

Cheers,
Michael
