### ISSUE TITLE
Error 'position' parameter & notebook crashes when getOctreeRep()

### ISSUE THREAD

**Issue by celinede** [mhogg/pyoctree#8]
Hi,
I don't manage to get the position parameter.
Here is what I get for 'tree.root.position' (even for your example):

NameError                                 Traceback (most recent call last)
<ipython-input-15-25c1864b7e6f> in <module>()
----> 1 tree.root.position
pyoctree\pyoctree.pyx in pyoctree.pyoctree.PyOctnode.position.__get__ (pyoctree\pyoctree.cpp:8283)()
NameError: name 'np' is not defined

And do you have any idea about why the jupyter notebook crashes when I try to excute: 'tree.getOctreeRep()' ? What could be missing ?

Finally I was wondering if there would be some more documentation available ?

Please let me know if you need any more information.
Thanks for your help!
Céline

**Comment by mhogg** [comment]
Hi Celine,

Unfortunately there is no more documentation, but if let me know what you are trying to do I am happy to help or explain things that are unclear.

As to your current issue, your error with tree.root.position appears to be caused by the pyoctree module not being able to locate numpy (which is the "name 'np' is not defined"). Your error with tree.getOctreeRep() may be related, as np is also used in this function.

Can you tell me:
- Have you got numpy installed? What version? Is it located in the usual position on your system? 
- How did you install pyoctree? The python wheel?
- Are you on a Windows 64 bit pc? If not, what os?
- Have you got vtk installed? What version?

There are a number of people that use pyoctree without issues, so hopefully we can sort it out.

Cheers,
Michael

**Comment by celinede** [comment]
Thanks for your quick answer!

ok I had a problem with my vtk install ! 
After installing it properly with 'conda install -c anaconda vtk=6.3.0' I don't have errors anymore.

Thanks again
Céline
